### ISSUE TITLE
Crash on sertain numbers in playeractivity and notfication

### ISSUE THREAD

**Issue by perrello** [adneal/Apollo-CM#15]
When browsing songs in the audioplayer Apollo chrashes on some songs(mostly the onze without art)
Also when playing the song that makes the audioplayer chrash the notification is gone

Could not debug atm but will place a log if needed

**Comment by Avinash-Bhat** [comment]
I'm also facing the same. Some other guys are facing this too: (post at [G+](https://plus.google.com/110911526500456128531/posts/DTkgHNBbTXc))

The problem is that the Exception is thrown unexpectedly at different places. So I'll try to get some logcat entries

Starting this with exception thrown in `MusicPlayerHandler`:

```
E/AndroidRuntime( 1753): FATAL EXCEPTION: MusicPlayerHandler
E/AndroidRuntime( 1753): java.lang.IllegalStateException: Can't parcel a recycled bitmap
E/AndroidRuntime( 1753):    at android.graphics.Bitmap.checkRecycled(Bitmap.java:243)
E/AndroidRuntime( 1753):    at android.graphics.Bitmap.writeToParcel(Bitmap.java:1295)
E/AndroidRuntime( 1753):    at android.widget.RemoteViews$BitmapCache.writeBitmapsToParcel(RemoteViews.java:839)
E/AndroidRuntime( 1753):    at android.widget.RemoteViews.writeToParcel(RemoteViews.java:2347)
E/AndroidRuntime( 1753):    at android.app.Notification.writeToParcel(Notification.java:719)
E/AndroidRuntime( 1753):    at android.app.ActivityManagerProxy.setServiceForeground(ActivityManagerNative.java:2711)
E/AndroidRuntime( 1753):    at android.app.Service.startForeground(Service.java:643)
E/AndroidRuntime( 1753):    at com.andrew.apollo.NotificationHelper.buildNotification(NotificationHelper.java:111)
E/AndroidRuntime( 1753):    at com.andrew.apollo.MusicPlaybackService.buildNotification(MusicPlaybackService.java:728)
E/AndroidRuntime( 1753):    at com.andrew.apollo.MusicPlaybackService$MusicPlayerHandler.handleMessage(MusicPlaybackService.java:2273)
E/AndroidRuntime( 1753):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1753):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1753):    at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by adneal** [comment]
Yeah, I've been looking into this. I'm not exactly sure why this happens at the moment.

**Comment by Avinash-Bhat** [comment]
It seems that the problem is with the notifications, IDK, I just experienced this issue starting yesterday, In the previous CM the app was different (Old one? i guess) anyway after the 17th nightly only the problem started.I wasn't being able to grab the logcats of the other crashes at that time. this is the newest one. anyway i'll try to add more.

**Comment by perrello** [comment]
I figured it out.. I think
The problemen accures in de offline lyricsprovider
When disabling the feature to save lyrics the chrash is gone

**Comment by adneal** [comment]
@locomain That class has nothing to do with the Bitmap in the notification bar that's throwing the error. It's only a coincidence.

**Comment by perrello** [comment]
@adneal haha oké! Just trying to help

**Comment by Avinash-Bhat** [comment]
@adneal ya, i was about to say that, the actual error may be the notification bar itself:
The actual errors was actually (if I recall correctly) was from exiting from the app, which causes the notification to appear.

**Comment by perrello** [comment]
O i was talking about an error that accures when browsing songs in the audioplayer
Not the behaviour of the notification

**Comment by Avinash-Bhat** [comment]
Got another crash entry

```
D/AndroidRuntime( 6769): Shutting down VM
W/dalvikvm( 6769): threadid=1: thread exiting with uncaught exception (group=0x41656930)
E/AndroidRuntime( 6769): FATAL EXCEPTION: main
E/AndroidRuntime( 6769): java.lang.RuntimeException: Unable to start service com.andrew.apollo.MusicPlaybackService@41a9ed50 with Intent { act=com.andrew.apollo.next flg=0x10000000 cmp=com.andrew.apollo/.MusicPlaybackService bnds=[376,595][454,667] }: java.lang.IllegalStateException: Can't parcel a recycled bitmap
E/AndroidRuntime( 6769):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2800)
E/AndroidRuntime( 6769):    at android.app.ActivityThread.access$1900(ActivityThread.java:153)
E/AndroidRuntime( 6769):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E/AndroidRuntime( 6769):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6769):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 6769):    at android.app.ActivityThread.main(ActivityThread.java:5226)
E/AndroidRuntime( 6769):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6769):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 6769):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 6769):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/AndroidRuntime( 6769):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 6769): Caused by: java.lang.IllegalStateException: Can't parcel a recycled bitmap
E/AndroidRuntime( 6769):    at android.graphics.Bitmap.checkRecycled(Bitmap.java:243)
E/AndroidRuntime( 6769):    at android.graphics.Bitmap.writeToParcel(Bitmap.java:1295)
E/AndroidRuntime( 6769):    at android.widget.RemoteViews$BitmapCache.writeBitmapsToParcel(RemoteViews.java:839)
E/AndroidRuntime( 6769):    at android.widget.RemoteViews.writeToParcel(RemoteViews.java:2347)
E/AndroidRuntime( 6769):    at android.app.Notification.writeToParcel(Notification.java:719)
E/AndroidRuntime( 6769):    at android.app.ActivityManagerProxy.setServiceForeground(ActivityManagerNative.java:2711)
E/AndroidRuntime( 6769):    at android.app.Service.startForeground(Service.java:643)
E/AndroidRuntime( 6769):    at com.andrew.apollo.NotificationHelper.buildNotification(NotificationHelper.java:111)
E/AndroidRuntime( 6769):    at com.andrew.apollo.MusicPlaybackService.buildNotification(MusicPlaybackService.java:728)
E/AndroidRuntime( 6769):    at com.andrew.apollo.MusicPlaybackService.play(MusicPlaybackService.java:1866)
E/AndroidRuntime( 6769):    at com.andrew.apollo.MusicPlaybackService.gotoNext(MusicPlaybackService.java:1913)
E/AndroidRuntime( 6769):    at com.andrew.apollo.MusicPlaybackService.handleCommandIntent(MusicPlaybackService.java:691)
E/AndroidRuntime( 6769):    at com.andrew.apollo.MusicPlaybackService.onStartCommand(MusicPlaybackService.java:674)
E/AndroidRuntime( 6769):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2783)
E/AndroidRuntime( 6769):    ... 10 more
I/AudioService( 2182):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@41af8698
D/SizeAdaptiveLayout( 2298): com.android.internal.widget.SizeAdaptiveLayout{41da4820 V.E..... ......I. 0,0-0,0 #7f090072 app:id/adaptive}child view android.widget.FrameLayout{42354448 G.E..... ......ID 0,0-0,0 #1020324 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/SizeAdaptiveLayout( 2298): com.android.internal.widget.SizeAdaptiveLayout{41da4820 V.E..... ......I. 0,0-0,0 #7f090072 app:id/adaptive}child view android.widget.FrameLayout{42354448 G.E..... ......ID 0,0-0,0 #1020324 android:id/status_bar_latest_event_content} measured out of bounds at 95px clamped to 96px
D/lights  ( 2182): set_light_buttons off
D/lights  ( 2182): set_light_buttons on=1
I/Process ( 6769): Sending signal. PID: 6769 SIG: 9
D/TinyALSA-Audio Output( 1844): audio_out_get_latency(0x40fd8d58)
W/InputMethodManagerService( 2182): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42200628 attribute=null, token = android.os.BinderProxy@423d66e8
W/AudioService( 2182):   RemoteControlClient died
W/AudioService( 2182):   AudioFocus   audio focus client died
I/ActivityManager( 2182): Process com.andrew.apollo:main (pid 6769) has died.
I/AudioService( 2182):  AudioFocus  abandonAudioFocus(): removing entry for android.media.AudioManager@41a9f6d8com.andrew.apollo.MusicPlaybackService$4@41a9ee98
W/ActivityManager( 2182): Scheduling restart of crashed service com.andrew.apollo/.MusicPlaybackService in 26104ms
D/TinyALSA-Audio Output( 1844): audio_out_get_latency(0x40fd8d58)
D/TinyALSA-Audio Output( 1844): audio_out_get_latency(0x40fd8d58)
W/MessageQueue( 2298): Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {41d0e208} sending message to a Handler on a dead thread
W/MessageQueue( 2298): java.lang.RuntimeException: Handler (android.media.AudioManager$FocusEventHandlerDelegate$1) {41d0e208} sending message to a Handler on a dead thread
W/MessageQueue( 2298):  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:294)
W/MessageQueue( 2298):  at android.os.Handler.enqueueMessage(Handler.java:618)
W/MessageQueue( 2298):  at android.os.Handler.sendMessageAtTime(Handler.java:587)
W/MessageQueue( 2298):  at android.os.Handler.sendMessageDelayed(Handler.java:558)
W/MessageQueue( 2298):  at android.os.Handler.sendMessage(Handler.java:495)
W/MessageQueue( 2298):  at android.media.AudioManager$1.dispatchAudioFocusChange(AudioManager.java:1894)
W/MessageQueue( 2298):  at android.media.IAudioFocusDispatcher$Stub.onTransact(IAudioFocusDispatcher.java:57)
W/MessageQueue( 2298):  at android.os.Binder.execTransact(Binder.java:351)
W/MessageQueue( 2298):  at dalvik.system.NativeStart.run(Native Method)
W/AudioFlinger( 1844): session id 1758 not found for pid 1844
```

_How I crashed it_: skip the songs really fast in the widget(my method) or in the notification bar(as said in the G+ post I shared above)

**Comment by darkrob** [comment]
I have the same problem and I also found out that the player will crash if you skip some titles (4-5 times) and then it becomes unresponsive and crashes. I also think that is has to do with the notification-bar-widget...

**Comment by adneal** [comment]
This has been fixed.

**Comment by darkrob** [comment]
I will test it with the newest nightly build today and report here...

**Comment by darkrob** [comment]
After deleting all app-data it works like a charme on my I9300 with the actual nightly 20130320...

Thank you for the great work!

**Comment by Avinash-Bhat** [comment]
This fix Introduces bug #18.

**Comment by eaglebooy** [comment]
hi i have the same problem , how did it fixed?

01-20 16:44:21.636 W/InputManagerService(321): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2c0f8760
01-20 16:44:21.646 W/AudioService(321):   AudioFocus   audio focus client died
01-20 16:44:21.646 I/AudioService(321):  AudioFocus  abandonAudioFocus(): removing entry for android.media.AudioManager@2be3fcd0com.andrew.apollo.MusicPlaybackService$2@2be69e08
01-20 16:44:21.646 W/AudioFlinger(157): session id 88 not found for pid 157
01-20 16:44:21.646 I/ActivityManager(321): Process com.andrew.apollo.plus:main (pid 1852) has died.
01-20 16:44:21.646 W/ActivityManager(321): Scheduling restart of crashed service com.andrew.apollo.plus/com.andrew.apollo.MusicPlaybackService in 5000ms
01-20 16:44:21.656 W/AudioService(321):   RemoteControlClient died
01-20 16:44:21.656 W/AudioService(321): Dead client in setNewRcClientGenerationOnClients_syncRcsCurrc()android.os.DeadObjectException

**Comment by ljian** [comment]
how to fix this?
