### ISSUE TITLE
Issue with album art extraction exception and player reloading

### ISSUE THREAD

**Issue by Avinash-Bhat** [adneal/Apollo-CM#18]
The following exception occur while trying to play a track with some weird album art.

The crash causes the media process to reload apollo. which in turn crashes, then again... ("crash loop"?) until you kill the media process.

```
W/dalvikvm( 4072): threadid=1: thread exiting with uncaught exception (group=0x411ea930)
 2E/AndroidRuntime( 4072): FATAL EXCEPTION: main
 3E/AndroidRuntime( 4072): java.lang.NullPointerException
 4E/AndroidRuntime( 4072):        at android.os.Parcel.readException(Parcel.java:1431)
 5E/AndroidRuntime( 4072):        at android.os.Parcel.readException(Parcel.java:1379)
 6E/AndroidRuntime( 4072):        at com.andrew.apollo.IApolloService$Stub$Proxy.open(IApolloService.java:373)
 7E/AndroidRuntime( 4072):        at com.andrew.apollo.utils.MusicUtils.playAll(MusicUtils.java:585)
 8E/AndroidRuntime( 4072):        at com.andrew.apollo.ui.fragments.SongFragment.onItemClick(SongFragment.java:268)
 9E/AndroidRuntime( 4072):        at android.widget.AdapterView.performItemClick(AdapterView.java:298)
10E/AndroidRuntime( 4072):        at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
11E/AndroidRuntime( 4072):        at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
12E/AndroidRuntime( 4072):        at android.widget.AbsListView$1.run(AbsListView.java:3423)
13E/AndroidRuntime( 4072):        at android.os.Handler.handleCallback(Handler.java:725)
14E/AndroidRuntime( 4072):        at android.os.Handler.dispatchMessage(Handler.java:92)
15E/AndroidRuntime( 4072):        at android.os.Looper.loop(Looper.java:137)
16E/AndroidRuntime( 4072):        at android.app.ActivityThread.main(ActivityThread.java:5226)
17E/AndroidRuntime( 4072):        at java.lang.reflect.Method.invokeNative(Native Method)
18E/AndroidRuntime( 4072):        at java.lang.reflect.Method.invoke(Method.java:511)
19E/AndroidRuntime( 4072):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
20E/AndroidRuntime( 4072):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
21E/AndroidRuntime( 4072):        at dalvik.system.NativeStart.main(Native Method)
22W/ActivityManager( 2236):   Force finishing activity com.andrew.apollo/.ui.activities.HomeActivity
```

**Comment by Avinash-Bhat** [comment]
If i subsequently try to play the same track aforementioned the exception changes to: 

```
E/AndroidRuntime( 4086): FATAL EXCEPTION: main
E/AndroidRuntime( 4086): java.lang.RuntimeException: Unable to start service com.andrew.apollo.MusicPlaybackService@414e0e60 with Intent { act=com.andrew.apollo.previous cmp=com.andrew.apollo/.MusicPlaybackService }: java.lang.NullPointerException
E/AndroidRuntime( 4086):                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2800)
E/AndroidRuntime( 4086):                 at android.app.ActivityThread.access$1900(ActivityThread.java:153)
E/AndroidRuntime( 4086):                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
E/AndroidRuntime( 4086):                 at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4086):                 at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 4086):                 at android.app.ActivityThread.main(ActivityThread.java:5226)
E/AndroidRuntime( 4086):                 at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4086):                 at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 4086):                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 4086):                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
E/AndroidRuntime( 4086):                 at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4086): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 4086):    at android.graphics.Bitmap.copy(Bitmap.java:442)
E/AndroidRuntime( 4086):    at com.andrew.apollo.MusicPlaybackService.updateRemoteControlClient(MusicPlaybackService.java:1280)
E/AndroidRuntime( 4086):    at com.andrew.apollo.MusicPlaybackService.notifyChange(MusicPlaybackService.java:1232)
E/AndroidRuntime( 4086):    at com.andrew.apollo.MusicPlaybackService.prev(MusicPlaybackService.java:1946)
E/AndroidRuntime( 4086):    at com.andrew.apollo.MusicPlaybackService.handleCommandIntent(MusicPlaybackService.java:694)
E/AndroidRuntime( 4086):    at com.andrew.apollo.MusicPlaybackService.onStartCommand(MusicPlaybackService.java:674)
E/AndroidRuntime( 4086):    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2783)
E/AndroidRuntime( 4086):    ... 10 more
E/MetadataRetrieverClient( 1853): failed to extract an album art
E/MetadataRetrieverClient( 1853): failed to extract an album art
E/MetadataRetrieverClient( 1853): failed to extract an album art
E/MetadataRetrieverClient( 1853): failed to extract an album art

```

**Comment by Avinash-Bhat** [comment]
The `NullPointerException` is removed with http://review.cyanogenmod.org/#/c/34179/
