### ISSUE TITLE
Force close on play ICS devices 

### ISSUE THREAD

**Issue by perrello** [adneal/Apollo-CM#25]
E/JavaBinder(11008): **\* Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder(11008): java.lang.NoSuchMethodError: android.content.ContentResolver.query
E/JavaBinder(11008):    at com.andrew.apollo.MusicPlaybackService.a(Unknown Source)
E/JavaBinder(11008):    at com.andrew.apollo.MusicPlaybackService.a(Unknown Source)
E/JavaBinder(11008):    at com.andrew.apollo.MusicPlaybackService.a(Unknown Source)
E/JavaBinder(11008):    at com.andrew.apollo.MusicPlaybackService.b(Unknown Source)
E/JavaBinder(11008):    at com.andrew.apollo.MusicPlaybackService.open(Unknown Source)
E/JavaBinder(11008):    at com.andrew.apollo.j.open(Unknown Source)
E/JavaBinder(11008):    at com.andrew.apollo.IApolloService$Stub.onTransact(Unknown Source)
E/JavaBinder(11008):    at android.os.Binder.execTransact(Binder.java:338)
E/JavaBinder(11008):    at dalvik.system.NativeStart.run(Native Method)
W/dalvikvm(11008): threadid=10: thread exiting with uncaught exception (group=0x40a4a1f8)
E/AndroidRuntime(11008): FATAL EXCEPTION: Binder Thread #2
E/AndroidRuntime(11008): java.lang.NoSuchMethodError: android.content.ContentResolver.query
E/AndroidRuntime(11008):    at com.andrew.apollo.MusicPlaybackService.a(Unknown Source)
E/AndroidRuntime(11008):    at com.andrew.apollo.MusicPlaybackService.a(Unknown Source)
E/AndroidRuntime(11008):    at com.andrew.apollo.MusicPlaybackService.a(Unknown Source)
E/AndroidRuntime(11008):    at com.andrew.apollo.MusicPlaybackService.b(Unknown Source)
E/AndroidRuntime(11008):    at com.andrew.apollo.MusicPlaybackService.open(Unknown Source)
E/AndroidRuntime(11008):    at com.andrew.apollo.j.open(Unknown Source)
E/AndroidRuntime(11008):    at com.andrew.apollo.IApolloService$Stub.onTransact(Unknown Source)
E/AndroidRuntime(11008):    at android.os.Binder.execTransact(Binder.java:338)
E/AndroidRuntime(11008):    at dalvik.system.NativeStart.run(Native Method)
D/dalvikvm(10509): GC_FOR_ALLOC freed 299K, 24% free 7721K/10119K, paused 91ms
D/dalvikvm(10992): GC_CONCURRENT freed 2362K, 39% free 8242K/13319K, paused 4ms+15ms
D/NetlinkEvent(  753): Unexpected netlink message. type=0x0
D/NetlinkEvent(  753): Unexpected netlink message. type=0x0
I/Process (11008): Sending signal. PID: 11008 SIG: 9
W/AudioService(  864):   RemoteControlClient died
I/ActivityManager(  864): Process com.andrew.apollo:main (pid 11008) has died.
W/ActivityManager(  864): Scheduling restart of crashed service com.andrew.apollo/.MusicPlaybackService in 5000ms
W/InputManagerService(  864): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@40eef430
I/dalvikvm(10992): Jit: resizing JitTable from 2048 to 4096
I/ActivityManager(  864): Start proc com.andrew.apollo:main for service com.andrew.apollo/.MusicPlaybackService: pid=11087 uid=10072 gids={1015, 3003}

**Comment by MelvynEzi** [comment]
This repo is at least not updated for 11 months. The latest commit which allows the app to run on ICS devices is 7 months ago (in CM's repo).

**Comment by perrello** [comment]
I put the issue here because Andrew is the original developer of Apollo.. And the cm's repo of Apollo has the minimum sdk set to 14 wich is ics:) but i cant add issues on that repo
